# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from ruamel.yaml import comments
from .base import Calico

SpecNode = comments.CommentedMap


def get_comment_value(node: SpecNode, *, name: str, field: str) -> str: ...

def parse_spec(content: str) -> Calico: ...
