# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from typing import Optional, Tuple


def execute_command(
        command: str,
        timeout: Optional[int] = ...
) -> Tuple[str, int, bool]: ...
