# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from typing import Iterable, Optional, Tuple


def execute_command(
        command: str,
        timeout: Optional[int] = ...
) -> Tuple[str, int, bool]: ...

def run_script(
        command: str,
        script: Iterable[str]
) -> Tuple[int, Iterable[str]]: ...
